import React, { useState, useRef, useEffect } from 'react';
import { useToast } from './Toast';

export interface ExportData {
  title: string;
  score?: number;
  dimensions?: Record<string, number>;
  content: string;
  changes?: string[];
  variants?: { version: string; post: string; angle: string }[];
}

interface ExportMenuProps {
  data: ExportData;
}

function buildMarkdown(data: ExportData): string {
  const lines: string[] = [];
  lines.push(`# Engagix Report`);
  lines.push('');
  lines.push(`## ${data.title}`);
  lines.push('');

  if (data.score !== undefined) {
    lines.push(`**Overall Score:** ${data.score}/100`);
    lines.push('');
  }

  if (data.dimensions) {
    lines.push('### Dimension Breakdown');
    lines.push('');
    for (const [key, val] of Object.entries(data.dimensions)) {
      const label = key.charAt(0).toUpperCase() + key.slice(1);
      lines.push(`- **${label}:** ${val}/100`);
    }
    lines.push('');
  }

  if (data.changes && data.changes.length > 0) {
    lines.push('### Changes Made');
    lines.push('');
    data.changes.forEach((c) => lines.push(`- ${c}`));
    lines.push('');
  }

  if (data.variants && data.variants.length > 0) {
    lines.push('### Variants');
    lines.push('');
    data.variants.forEach((v) => {
      lines.push(`#### Variant ${v.version} — ${v.angle}`);
      lines.push('');
      lines.push(v.post);
      lines.push('');
    });
  }

  if (data.content) {
    lines.push('### Content');
    lines.push('');
    lines.push(data.content);
    lines.push('');
  }

  lines.push('---');
  lines.push(`*Generated by Engagix — ${new Date().toLocaleString()}*`);

  return lines.join('\n');
}

function buildPlainText(data: ExportData): string {
  const lines: string[] = [];
  lines.push('ENGAGEBOOST AI REPORT');
  lines.push('='.repeat(40));
  lines.push('');
  lines.push(data.title);
  lines.push('');

  if (data.score !== undefined) {
    lines.push(`Overall Score: ${data.score}/100`);
    lines.push('');
  }

  if (data.dimensions) {
    lines.push('Dimension Breakdown:');
    for (const [key, val] of Object.entries(data.dimensions)) {
      const label = key.charAt(0).toUpperCase() + key.slice(1);
      lines.push(`  ${label}: ${val}/100`);
    }
    lines.push('');
  }

  if (data.changes && data.changes.length > 0) {
    lines.push('Changes Made:');
    data.changes.forEach((c) => lines.push(`  - ${c}`));
    lines.push('');
  }

  if (data.variants && data.variants.length > 0) {
    lines.push('Variants:');
    data.variants.forEach((v) => {
      lines.push(`  [${v.version}] ${v.angle}`);
      lines.push(`  ${v.post}`);
      lines.push('');
    });
  }

  if (data.content) {
    lines.push('Content:');
    lines.push(data.content);
    lines.push('');
  }

  lines.push('-'.repeat(40));
  lines.push(`Generated by Engagix — ${new Date().toLocaleString()}`);

  return lines.join('\n');
}

export const ExportMenu: React.FC<ExportMenuProps> = ({ data }) => {
  const [open, setOpen] = useState(false);
  const menuRef = useRef<HTMLDivElement>(null);
  const { toast } = useToast();

  // Close on outside click
  useEffect(() => {
    if (!open) return;
    const handler = (e: MouseEvent) => {
      if (menuRef.current && !menuRef.current.contains(e.target as Node)) {
        setOpen(false);
      }
    };
    document.addEventListener('mousedown', handler);
    return () => document.removeEventListener('mousedown', handler);
  }, [open]);

  const handleCopyMarkdown = async () => {
    try {
      await navigator.clipboard.writeText(buildMarkdown(data));
      toast('Markdown copied to clipboard!', 'success');
    } catch {
      toast('Failed to copy', 'error');
    }
    setOpen(false);
  };

  const handleDownloadTxt = () => {
    const text = buildPlainText(data);
    const blob = new Blob([text], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `engageboost-report-${Date.now()}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    toast('Report downloaded!', 'success');
    setOpen(false);
  };

  const handlePrintPDF = () => {
    // Inject print-specific data attributes for the @media print styles
    document.documentElement.setAttribute('data-print-title', data.title);
    document.documentElement.setAttribute('data-print-score', String(data.score ?? ''));
    window.print();
    toast('Print dialog opened', 'info');
    setOpen(false);
  };

  return (
    <div className="export-menu-wrap" ref={menuRef}>
      <button
        onClick={() => setOpen(!open)}
        className="export-menu-trigger"
        aria-label="Export results"
        aria-expanded={open}
        aria-haspopup="true"
        title="Export results"
      >
        <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
          <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
          <polyline points="7 10 12 15 17 10" />
          <line x1="12" y1="15" x2="12" y2="3" />
        </svg>
      </button>

      {open && (
        <div className="export-menu-dropdown" role="menu">
          <button onClick={handleCopyMarkdown} className="export-menu-item" role="menuitem">
            <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
              <rect x="9" y="9" width="13" height="13" rx="2" ry="2" />
              <path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1" />
            </svg>
            Copy Markdown
          </button>
          <button onClick={handleDownloadTxt} className="export-menu-item" role="menuitem">
            <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
              <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z" />
              <polyline points="14 2 14 8 20 8" />
              <line x1="16" y1="13" x2="8" y2="13" />
              <line x1="16" y1="17" x2="8" y2="17" />
            </svg>
            Download .txt
          </button>
          <button onClick={handlePrintPDF} className="export-menu-item" role="menuitem">
            <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
              <polyline points="6 9 6 2 18 2 18 9" />
              <path d="M6 18H4a2 2 0 0 1-2-2v-5a2 2 0 0 1 2-2h16a2 2 0 0 1 2 2v5a2 2 0 0 1-2 2h-2" />
              <rect x="6" y="14" width="12" height="8" />
            </svg>
            Print PDF
          </button>
        </div>
      )}
    </div>
  );
};
